
name: Sync flomo from Notion database to Readwise

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 16 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sync flomo from Notion database to Readwise
      run: python starter.py
      env:
        NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_INTEGRATION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        READWISE_ACCESS_TOKEN: ${{ secrets.READWISE_ACCESS_TOKEN }}
        OBSIDIAN_SYNC_GITHUB_TOKEN: ${{ secrets.OBSIDIAN_SYNC_GITHUB_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update sync time and log
